# k8s/services/modsecurity-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: modsecurity-waf
  namespace: juice-shop-waf
spec:
  selector:
    app: modsecurity-waf
  ports:
  - port: 9090
    targetPort: 8080
    name: http
  type: LoadBalancer
